test_that("use", {
  expect_silent(check_window_kb(0.000))
  expect_silent(check_window_kb(0.001))
  expect_silent(check_window_kb(0))
  expect_silent(check_window_kb(1))
  expect_silent(check_window_kb(2))
  expect_error(check_window_kb(0.0001))
  expect_error(check_window_kb(0.00001))
  expect_error(check_window_kb(-3))
  expect_error(check_window_kb("nonsense"))
  expect_error(check_window_kb(""))
  expect_error(check_window_kb(NULL))
  expect_error(check_window_kb(NA))
  expect_error(check_window_kb(Inf))
  expect_error(check_window_kb(c(1, 2)))
})
