test_that("use", {
  expect_silent(check_phenotypes("random"))
  expect_silent(check_phenotypes("additive"))
  expect_silent(check_phenotypes(c("random", "additive")))
  expect_silent(check_phenotypes(get_phenotypes()))
  expect_silent(check_phenotypes("nonsense"))
  expect_error(check_phenotypes(""))
  expect_error(check_phenotypes(NA))
  expect_error(check_phenotypes(NULL))
  expect_error(check_phenotypes(Inf))
  expect_error(check_phenotypes(3.14))
  expect_error(check_phenotypes(42))
  expect_error(check_phenotypes(c("random", "")))
})
