test_that("use", {
  expect_silent(check_confidence_interval(confidence_interval = 0.95))
  expect_silent(check_confidence_interval(0.99))
  expect_silent(check_confidence_interval(0.91))
  expect_error(check_confidence_interval(0.0))
  expect_error(check_confidence_interval(1.0))
  expect_error(check_confidence_interval(NULL))
  expect_error(check_confidence_interval(NA))
  expect_error(check_confidence_interval(Inf))
  expect_error(check_confidence_interval(""))
  expect_error(check_confidence_interval("nonsense"))
  expect_error(check_confidence_interval(c()))
  expect_error(check_confidence_interval(c(0.95, 0.95)))
})
