test_that("use", {
  expect_silent(check_ld_window_r2(0.0))
  expect_silent(check_ld_window_r2(0.6))
  expect_silent(check_ld_window_r2(1.0))
  expect_error(check_ld_window_r2(TRUE))
  expect_error(check_ld_window_r2(FALSE))
  expect_error(check_ld_window_r2(-0.3))
  expect_error(check_ld_window_r2(""))
  expect_error(check_ld_window_r2("nonsense"))
  expect_error(check_ld_window_r2(NULL))
  expect_error(check_ld_window_r2(NA))
  expect_error(check_ld_window_r2(Inf))
  expect_error(check_ld_window_r2(c(0.1, 0.2)))
})
