on:
  push:
  pull_request:

name: build_singularity

jobs:
  build_singularity:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        singularity_version:
          - '3.7.4'
    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Show singularity version
        run: singularity version

      - name: Build Container
        env:
          SINGULARITY_RECIPE: Singularity
          OUTPUT_CONTAINER: plinkr.sif
        run: |
         ls 
         if [ -f "${SINGULARITY_RECIPE}" ]; then
              sudo -E singularity build ${OUTPUT_CONTAINER} ${SINGULARITY_RECIPE}
         else
             echo "${SINGULARITY_RECIPE} is not found."
             echo "Present working directory: $PWD"
             ls
         fi

      - name: Run container
        run: singularity run plinkr.sif

