# Check if the versions match between the different files

on:
  push:
  pull_request:

name: check_versions_match

jobs:
  check_versions_match:

    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install dependencies
        run: |
          install.packages(c("stringr", "readr", "testthat"))
        shell: Rscript {0}

      - name: Check that versions match
        run: Rscript scripts/check_versions_match.R

