# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 28 * *"

name: R-CMD-check

jobs:
  R-CMD-check:

    strategy:
      fail-fast: false
      matrix:
        install_plink: [true, false]
        os: [ubuntu-latest]

    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install libgit2-dev
        run: sudo apt install -qq libgit2-dev

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_github("OchoaLab/genio")
          remotes::install_github("chrchang/plink-ng/2.0/pgenlibr")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
          remotes::install_cran("covr")
          remotes::install_cran("lintr")
          remotes::install_github("MangoTheCat/goodpractice")
        shell: Rscript {0}

      - name: Install PLINKs
        env:
          INSTALL_PLINK: ${{ matrix.install_plink }}
        run: if [[ "$INSTALL_PLINK" == true ]]; then ./scripts/install_plinks.sh; fi

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}

      - name: Test coverage
        env:
          INSTALL_PLINK: ${{ matrix.install_plink }}
        run: if [[ "$INSTALL_PLINK" == true ]]; then Rscript -e "covr::codecov()"; fi

      - name: Lint
        run: lintr::lint_package()
        shell: Rscript {0}

      - name: Install plinkr
        run: remotes::install_github("richelbilderbeek/plinkr")
        shell: Rscript {0}

      - name: Report
        run: plinkr::plinkr_report()
        shell: Rscript {0}

